import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { colors } from '../theme/palette';

function formatCurrency(value) {
  return `Php ${Math.round(value ?? 0).toLocaleString('en-PH')}`;
}

function sanitizeForFilename(text) {
  return text.trim().replace(/\s+/g, '_').replace(/[^\w-]/g, '');
}

function hexToRgb(hex) {
  const value = hex.replace('#', '');
  return [0, 2, 4].map((offset) => parseInt(value.slice(offset, offset + 2), 16));
}

/**
 * Builds and downloads a Bill of Materials PDF from data already computed
 * on the page — this function only renders what it's given, so it's
 * frontend-only for now (the page currently passes mocked figures) but
 * needs no changes once that data comes from a real backend instead.
 *
 * @param {object} bom
 * @param {string} bom.projectName
 * @param {Array<{label: string, value: string}>} bom.projectInfo Human-readable project facts.
 * @param {Array<{material: string, category: string, quantityLabel: string, unit: string, unitPrice: number, amount: number}>} bom.lineItems
 * @param {number} bom.grandTotal
 * @param {Date} [bom.generatedAt]
 */
export function generateBomPdf({ projectName, projectInfo, lineItems, grandTotal, generatedAt = new Date() }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const marginX = 40;
  const brandBlue = hexToRgb(colors.brandBlue);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...brandBlue);
  doc.text('ConstructEst', marginX, 46);

  doc.setFontSize(20);
  doc.setTextColor(20, 20, 20);
  doc.text(`${projectName}: Bill of Materials`, marginX, 78);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(110, 110, 110);
  const dateLabel = generatedAt.toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.text(`Date generated: ${dateLabel}`, marginX, 96);

  let infoY = 122;
  doc.setFontSize(11);
  projectInfo.forEach(({ label, value }) => {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text(`${label}:`, marginX, infoY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(20, 20, 20);
    doc.text(value, marginX + 110, infoY);
    infoY += 16;
  });

  autoTable(doc, {
    startY: infoY + 14,
    margin: { left: marginX, right: marginX },
    head: [['Material', 'Category', 'Quantity', 'Unit', 'Unit Cost', 'Total Cost']],
    body: lineItems.map((item) => [
      item.material,
      item.category,
      item.quantityLabel,
      item.unit,
      formatCurrency(item.unitPrice),
      formatCurrency(item.amount),
    ]),
    headStyles: { fillColor: brandBlue, textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 7, textColor: [40, 40, 40] },
    alternateRowStyles: { fillColor: [246, 248, 252] },
    columnStyles: {
      2: { halign: 'right' },
      4: { halign: 'right' },
      5: { halign: 'right' },
    },
  });

  const finalY = doc.lastAutoTable.finalY + 28;
  doc.setDrawColor(220, 220, 220);
  doc.line(marginX, finalY - 12, doc.internal.pageSize.getWidth() - marginX, finalY - 12);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text('Overall Estimated Project Cost', marginX, finalY);
  doc.setFontSize(15);
  doc.setTextColor(...brandBlue);
  doc.text(formatCurrency(grandTotal), marginX, finalY + 20);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text(
    'Generated by ConstructEst. Figures are estimates based on parsed floor plan data and current store pricing.',
    marginX,
    doc.internal.pageSize.getHeight() - 32,
  );

  doc.save(`Bill_of_Materials_${sanitizeForFilename(projectName)}.pdf`);
}
