import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { colors } from '../theme/palette';
import { formatAmount } from '../utils/formatNumbers';

// "Php " instead of the peso sign, since jsPDF's built-in fonts have no glyph
// for it. Amounts use the shared formatter so the PDF matches the on-screen table.
function formatCurrency(value) {
  return `Php ${formatAmount(value)}`;
}

function sanitizeForFilename(text) {
  return text.trim().replace(/\s+/g, '_').replace(/[^\w-]/g, '');
}

function hexToRgb(hex) {
  const value = hex.replace('#', '');
  return [0, 2, 4].map((offset) => parseInt(value.slice(offset, offset + 2), 16));
}

/**
 * Builds and downloads a Bill of Materials PDF from data already computed on
 * the page. It only renders what it is given.
 *
 * @param {object} bom
 * @param {string} bom.projectName
 * @param {Array<{label: string, value: string}>} bom.projectInfo Human-readable project facts.
 * @param {Array<{material: string, category: string, spec: string|null, available: boolean, quantityLabel: string, unit: string, unitPrice: number|null, amount: number|null}>} bom.lineItems
 * @param {number} bom.grandTotal
 * @param {Date} [bom.generatedAt]
 */
export function generateBomPdf({ projectName, projectInfo, lineItems, grandTotal, generatedAt = new Date() }) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const marginX = 40;
  const brandBlue = hexToRgb(colors.brandBlue);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...brandBlue);
  doc.text('ConstructEst', marginX, 46);

  doc.setFontSize(20);
  doc.setTextColor(20, 20, 20);
  doc.text(`${projectName}: Bill of Materials`, marginX, 78);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(110, 110, 110);
  const dateLabel = generatedAt.toLocaleDateString('en-PH', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.text(`Date generated: ${dateLabel}`, marginX, 96);

  let infoY = 122;
  doc.setFontSize(11);
  projectInfo.forEach(({ label, value }) => {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(60, 60, 60);
    doc.text(`${label}:`, marginX, infoY);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(20, 20, 20);
    doc.text(value, marginX + 110, infoY);
    infoY += 16;
  });

  autoTable(doc, {
    // Small gap under the project details (infoY is already one line below the last one).
    startY: infoY + 2,
    margin: { left: marginX, right: marginX },
    head: [['Material', 'Category', 'Spec', 'Quantity', 'Unit', 'Unit Cost', 'Total Cost']],
    body: lineItems.map((item) => [
      item.material,
      item.category,
      // Sand and gravel have no spec, so show a dash like the on-screen table.
      item.spec || '—',
      item.quantityLabel,
      item.unit,
      item.available === false ? 'Not available' : formatCurrency(item.unitPrice),
      item.available === false ? 'Not available' : formatCurrency(item.amount),
    ]),
    headStyles: { fillColor: brandBlue, textColor: [255, 255, 255], fontStyle: 'bold' },
    // Number headers line up with their right-aligned values.
    didParseCell: (data) => {
      if (data.section === 'head' && [3, 5, 6].includes(data.column.index)) data.cell.styles.halign = 'right';
    },
    styles: { fontSize: 9, cellPadding: 6, textColor: [40, 40, 40] },
    alternateRowStyles: { fillColor: [246, 248, 252] },
    columnStyles: {
      3: { halign: 'right' },
      // Fixed widths so amounts like "Php 182,030.00" stay on one line
      // (wrapped amounts made every row two lines tall). Spec takes the rest.
      5: { halign: 'right', cellWidth: 74 },
      6: { halign: 'right', cellWidth: 82 },
    },
  });

  // The total needs about 50 pt above the footer. If the table ends too low,
  // put the total at the top of a new page instead of over the footer.
  const pageHeight = doc.internal.pageSize.getHeight();
  let finalY = doc.lastAutoTable.finalY + 28;
  if (finalY + 20 > pageHeight - 50) {
    doc.addPage();
    finalY = 60;
  }
  doc.setDrawColor(220, 220, 220);
  doc.line(marginX, finalY - 12, doc.internal.pageSize.getWidth() - marginX, finalY - 12);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(20, 20, 20);
  doc.text('Overall Estimated Project Cost', marginX, finalY);
  doc.setFontSize(15);
  doc.setTextColor(...brandBlue);
  doc.text(formatCurrency(grandTotal), marginX, finalY + 20);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text(
    'Generated by ConstructEst. Figures are estimates based on parsed floor plan data and current store pricing.',
    marginX,
    pageHeight - 32,
  );

  doc.save(`Bill_of_Materials_${sanitizeForFilename(projectName)}.pdf`);
}
