import LegalPageLayout from '../features/legal/components/LegalPageLayout';

const SECTIONS = [
  {
    heading: '1. What ConstructEst is',
    body: 'ConstructEst is an academic capstone project built by BSIT–Web and Mobile Applications students at Tarlac State University. It is a rule-based tool that reads a 2D AutoCAD DXF floor plan and produces an estimated structural material quantity take-off, cost comparison across hardware stores, and a downloadable Bill of Materials. It is not a commercial product, and using it means you understand it was built, and is currently operated, for a student thesis project — including its testing and evaluation phase.',
  },
  {
    heading: '2. Accuracy and no professional substitute',
    body: 'Every quantity ConstructEst produces comes from a documented rule-based formula, not from a licensed structural engineer reviewing your specific building. Some inputs the system cannot derive from a 2D floor plan (e.g. exact beam dimensions, soil-dependent footing sizing) use stated defaults you can override, and a few formulas are documented approximations pending further validation. Nothing generated by this system is a substitute for a licensed civil engineer\'s sealed plans, and it should not be used as the sole basis for an actual construction budget or procurement decision.',
  },
  {
    heading: '3. Your account',
    body: 'You are responsible for the accuracy of the information you register with and for keeping your password confidential. Do not share your account, and let us know if you believe it has been compromised.',
  },
  {
    heading: '4. Acceptable use',
    body: 'Use the system only for its intended purpose — uploading your own floor plans, generating estimates, and comparing store pricing. Don\'t attempt to disrupt the service, probe it for vulnerabilities without permission, or upload files you don\'t have the right to use.',
  },
  {
    heading: '5. Your files and data',
    body: 'Floor plans you upload and the projects you create remain yours. We use them only to compute your estimate and, in aggregate and where you\'ve agreed to participate, to evaluate the system\'s accuracy and usability as part of the capstone\'s research objectives.',
  },
  {
    heading: '6. Changes',
    body: 'Because this is an active student project, features, formulas, and these terms may change as the system is developed and refined. Material changes will be reflected on this page.',
  },
  {
    heading: '7. Contact',
    body: 'Questions about these terms can be directed to the development team through your capstone panel or research adviser\'s usual channel of contact.',
  },
];

function TermsPage() {
  return <LegalPageLayout title="Terms of Service" updatedLabel="Last updated: September 2026" sections={SECTIONS} />;
}

export default TermsPage;
